### PR TITLE
Expand unsupported instructions in ISelLowering

### LINKED ISSUE #5: Legalize operations in Selection DAG properly
The compiler generates operations not supported by the target architecture and crashes.

Most of the operations are `Legal` by default which means that they need to have selection logic for the corresponding machine instructions. The former is true for `ISD::MUL` and `ISD::DIV`, but we do not have selection logic (or machine instructions) for them.

We need to go through the ISD node types that have `Legal` as their default legalization action in `TargetLoweringBase::initActions()` and either:
- set their action to `Custom` and add lowering logic (in `CDMISelLowering`);
- set their action to `Expand` or `LibCall`, if possible.

Do we need to implement library calls somewhere or do we leave it to the user? For example, using `LibCall` for `ISD::MUL`, generates a call to `__mulhi3`. Looks like functions like this are implemented in libgcc. LLVM's compiler-rt [has a software multiplication algorithm for RISC-V](https://github.com/ylab-nsu/cdm16-llvm-neo/blob/b5f47a007d17d2adaac3f8c35813462ea3cef95b/compiler-rt/lib/builtins/riscv/int_mul_impl.inc#L22). Rust's `compiler-builtins` crate [also has this](https://github.com/rust-lang/compiler-builtins/blob/82a32c6bd1b82b55de5aea0cddb707732b54855f/compiler-builtins/src/riscv.rs#L20).

### PR DESCRIPTION
**Pull request by NetscapeNav**
Updated CDM lowering and assembly generation:

CDMISelLowering.cpp:
- Configured 16-bit arithmetic operations MUL, DIV, REM to use LibCall
- Set multiplication operations SMUL_LOHI, UMUL_LOHI to Expand

CDMAsmPrinter.cpp:
- Added external symbol declaration for __mulhi3, __divhi3, __udivhi3 and other functions

closes #5

### CODE REVIEW

File: llvm/lib/Target/CDM/CDMISelLowering.cpp [hunk 1]
```diff
@@ -62,6 +62,47 @@ CDMISelLowering::CDMISelLowering(const CDMTargetMachine &TM,
...
+  setOperationAction(ISD::ATOMIC_LOAD_UMIN, MVT::i16, Expand);
+  
+  /*
+  setOperationAction(ISD::BSWAP, MVT::i16, Expand);
+  setOperationAction(ISD::CTLZ, MVT::i16, Expand);
+  setOperationAction(ISD::CTTZ, MVT::i16, Expand);
+  setOperationAction(ISD::CTPOP, MVT::i16, Expand);
+  
+  setOperationAction(ISD::ROTL, MVT::i16, Expand);
+  setOperationAction(ISD::ROTR, MVT::i16, Expand);
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMISelLowering.cpp]: We do support `ROTL` and `ROTR` natively.

Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMISelLowering.cpp]: We do support `ROTL` and `ROTR` natively.

File: llvm/lib/Target/CDM/CDMISelLowering.cpp [hunk 2]
```diff
@@ -62,6 +62,47 @@ CDMISelLowering::CDMISelLowering(const CDMTargetMachine &TM,
...
+
+  setOperationAction(ISD::SHL, MVT::i16, Custom);
+  setOperationAction(ISD::SRA, MVT::i16, Custom);
+  setOperationAction(ISD::SRL, MVT::i16, Custom);
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMISelLowering.cpp]: We don't custom-expand bit shifts.

**Review by aelsi2 — CHANGES_REQUESTED** [review]
There are missing `ext` declarations for multiplication/division functions. There are also a lot of missing `ext`s for atomic ops.

Please, add the missing `ext` declarations for multiplication/division, but not other functions. I don't think it makes sense to add hard-coded `ext`s for all of libcalls. At some point we're going to lose track of them (we kinda already did). We should instead add `ext` generation in our custom `MCStreamer` (#18).

Also please rebase again. I've recently merged dynamic stack allocation support into main, and there are several changes to the constructor of `CDMISelLowering`.

File: llvm/lib/Target/CDM/CDMISelLowering.cpp [hunk 3]
```diff
@@ -62,6 +62,45 @@ CDMISelLowering::CDMISelLowering(const CDMTargetMachine &TM,
...
+  setOperationAction(ISD::UMUL_LOHI, MVT::i16, Expand);
+  setOperationAction(ISD::MULHS, MVT::i16, Expand);
+  setOperationAction(ISD::MULHU, MVT::i16, Expand);
+
+  setOperationAction(ISD::MUL, MVT::i32, Expand);
+  setOperationAction(ISD::MUL, MVT::i64, Expand);
+  setOperationAction(ISD::SMUL_LOHI, MVT::i32, Expand);
+  setOperationAction(ISD::UMUL_LOHI, MVT::i32, Expand);
+  setOperationAction(ISD::SMUL_LOHI, MVT::i64, Expand);
+  setOperationAction(ISD::UMUL_LOHI, MVT::i64, Expand);
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMISelLowering.cpp]: Why are these there? AFAIK, LLVM auto-expands 32-bit and 64-bit ops because we have only 16-bit registers, and you don't need to specify `Expand` explicitly.

**Review by aelsi2 — APPROVED** [review]
