### PR TITLE
Large stack alloc fix & emergency spill fix & minor improvement

### LINKED ISSUE #33: Le Big stack frames returns. Stack frame allocation produces out of bound immediate for addsp instruction.
Following code:
```c
void bar(int*);

void foo() {
  int arr[513];
  bar(arr);

  return;
}
```

Produces (with -O2 but irrelevant):

```
foo>
# %bb.0:
        push    fp
        ldsp    fp
        addsp   -1026
        addsp   -8
        ldi     r0, -1026
        add     r0, fp, r0
        jsr     bar
        addsp   8
        addsp   1026
        pop     fp
        rts
```

While immediate range for `addsp` instruction is [-1024; 1024]

### LINKED ISSUE #34: Cannot scavenge register without an emergency spill slot when compiling core with Rustc
Compilation of `core` with rustc fails with an LLVM error:

```txt
rustc-LLVM ERROR: Error while trying to spill R2 from class CPURegs: Cannot scavenge register without an emergency spill slot!
```

When compiling the generated IR with `llc`, it's the same error, but a different register:
```txt
LLVM ERROR: Error while trying to spill R4 from class CPURegs: Cannot scavenge register without an emergency spill slot!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./Documents/projects/cpp/cdm16-llvm-neo/llvm/build/bin/llc core.ll -O2
1.      Running pass 'Function Pass Manager' on module 'core.ll'.
2.      Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@_ZN4core3num7dec2flt7decimal7Decimal13try_fast_path17hbbac9ab0cfab2784E'
```

### LINKED ISSUE #44: Unaddressable stack sizes
It is possible to create entirely unaddressable stack frames:

```c
int foo() {
  char _frame1[32768];
  char _frame2[32768];

  use(_frame1);
  use(_frame2);

  int x = 10;

  bar(&x);

  return x;
}
```

->

```
foo>                                    # -- Begin function foo
# %bb.0:                                # %entry
	push	fp
	ldsp	fp
	addsp	-65538 # mentioned in another issue
	addsp	-8
	ldi	r0, -32768 # fine
	add	r0, fp, r0
	jsr	use
	addsp	8
	addsp	-8
	ldi	r0, -65536 # not fine !
	add	r0, fp, r0
	jsr	use
	addsp	8
	ldi	r0, 10
	ldi	r1, -65538 # !
	stw	r1, fp, r0
	ldi	r0, -65538 # !
	add	r0, fp, r0
	addsp	-8
	jsr	bar
	addsp	8
	ldi	r1, -65538 # !
	ldw	r1, fp, r0
	addsp	65538
	stsp	fp
	pop	fp
	rts
```

### PR DESCRIPTION
**Pull request by sxrose**
done some stack stuff idk
closes #33
closes #34 
closes #44

### CODE REVIEW

File: llvm/lib/Target/CDM/CDMFrameLowering.h [hunk 1]
```diff
@@ -21,11 +23,13 @@ class CDMFrameLowering : public TargetFrameLowering {
   MachineBasicBlock::iterator
   eliminateCallFramePseudoInstr(MachineFunction &MF, MachineBasicBlock &MBB,
                                 MachineBasicBlock::iterator MI) const override;
+
 protected:
   bool hasFPImpl(const MachineFunction &MF) const override;
 
 private:
   const CDMSubtarget &STI;
+  static void checkStackFrameSize(const MachineFunction &MF);
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMFrameLowering.h]: Maybe rename this to `ensureStackFrameNotTooLarge` to make it clearer what it does.

File: llvm/lib/Target/CDM/CDMInstrInfo.cpp [hunk 2]
```diff
@@ -223,30 +235,38 @@ void CDMInstrInfo::copyPhysReg(MachineBasicBlock &MBB,
...
-  MIB.addReg(DestReg);
-  MIB.addReg(SrcReg, getKillRegState(KillSrc));
+  BuildMI(MBB, MI, DL, get(CDM::MOVE), DestReg)
+      .addReg(SrcReg, getKillRegState(KillSrc));
 }
 
 void CDMInstrInfo::adjustStackPtr(int64_t Amount, MachineBasicBlock &MBB,
                                   MachineBasicBlock::iterator I,
                                   const DebugLoc &DL) const {
+  // addsp's (odly) use imm11 so
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMInstrInfo.cpp]: Misspelling: "odly"

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp [hunk 3]
```diff
@@ -72,78 +85,69 @@ bool CDMRegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
-      IsInvalidWordFPRelIns(MI.getOpcode(), SpOffset)) {
-    if (!RS) {
-      llvm_unreachable("RegScavenger must be initialised");
+                    << "FpOffset   : " << FpOffset << "\n"
+                    << "StackSize  : " << StackSize << "\n");
+
+  MI.getOperand(I).ChangeToImmediate(FpOffset);
+
+  // devil: my child will write switch-case like "they" want him to
+  // god: abuse c++ till the day you die son
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: This is unnecessary, the code is not even *that* bad.

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp [hunk 4]
```diff
@@ -72,78 +85,69 @@ bool CDMRegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
+          {CDM::ssb, {CDM::stbRR, 1}},   {CDM::lsb, {CDM::ldbRR, 1}},
+          {CDM::lssb, {CDM::ldsbRR, 1}},
+      };
+
+  const auto OpcodeFind =
+      std::map<unsigned, std::pair<unsigned, unsigned>>::const_iterator(
+          SubstitutionOpcsTable.find(
+              MI.getOpcode())); // because inline gods said so
+
+  if (OpcodeFind == SubstitutionOpcsTable.end())
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: Please don't do one line blocks without curly braces. It's gonna be more difficult to edit later and I just don't like them 🤓

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp [hunk 5]
```diff
@@ -158,4 +162,67 @@ CDMRegisterInfo::getCallPreservedMask(const MachineFunction &MF,
...
+Register CDMRegisterInfo::huntRegister(MachineBasicBlock &MBB,
+                                       const TargetRegisterClass &RC,
+                                       MachineBasicBlock::iterator MI,
+                                       bool AllowStackAdj) {
+  // TODO: handle inital sets (Used, GPR) thru info from tablegen (and put that
+  // info into fucking tablegen in a first place)
+  assert(MI->getParent() == &MBB && "MI must belong to the MBB");
+  assert(MI != MBB.end() && "MI must not be MBB.end()");
+
+  // r4-r6 are callee saved, so we can't initially asume they're available
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: Misspelling: "asume"

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp [hunk 6]
```diff
@@ -158,4 +162,67 @@ CDMRegisterInfo::getCallPreservedMask(const MachineFunction &MF,
...
+  SmallSet<Register, CDM::NUM_TARGET_REGS> Used{CDM::R4, CDM::R5, CDM::R6};
+
+  for (auto It = MBB.liveout_begin(); It != MBB.liveout_end(); ++It)
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: Single statement block ❌❌❌

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp [hunk 7]
```diff
@@ -158,4 +162,67 @@ CDMRegisterInfo::getCallPreservedMask(const MachineFunction &MF,
...
+    Used.insert(It->PhysReg);
+
+  for (auto It = std::prev(MBB.end()); It != MI; --It) {
+    for (MachineOperand Op : It->operands()) {
+      if (Op.isReg() && Op.getReg().isPhysical() && Op.isDef())
+        Used.erase(Op.getReg());
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: Nested single statement block ❌❌❌❌❌❌❌❌❌

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp [hunk 8]
```diff
@@ -158,4 +162,67 @@ CDMRegisterInfo::getCallPreservedMask(const MachineFunction &MF,
   llvm_unreachable("Unknown calling convention");
 }
 
+Register CDMRegisterInfo::huntRegister(MachineBasicBlock &MBB,
+                                       const TargetRegisterClass &RC,
+                                       MachineBasicBlock::iterator MI,
+                                       bool AllowStackAdj) {
+  // TODO: handle inital sets (Used, GPR) thru info from tablegen (and put that
+  // info into fucking tablegen in a first place)
```
Comment (aelsi2) [inline llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: You should probably open an issue.

**Review by aelsi2 — CHANGES_REQUESTED** [review]
```txt
Warning: [reviewdog] reported by reviewdog 🐶
```

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp (hunk 7 above)
Comment (ky1e-cyber) [reply llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: ok nested block is bad even for me haven't noticed it

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp [hunk 9]
```diff
@@ -72,78 +85,69 @@ bool CDMRegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
-  // If the immediate operand of ssw, lsw, ssb, lsb, lssb
-  // is out of bounds, perform a substitution
-  if (IsInvalidByteFPRelIns(MI.getOpcode(), SpOffset) ||
-      IsInvalidWordFPRelIns(MI.getOpcode(), SpOffset)) {
-    if (!RS) {
-      llvm_unreachable("RegScavenger must be initialised");
+                    << "FpOffset   : " << FpOffset << "\n"
+                    << "StackSize  : " << StackSize << "\n");
+
+  MI.getOperand(I).ChangeToImmediate(FpOffset);
```
[the remark this answers is not in the document]
Comment (ky1e-cyber) [reply llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: i moved it because of early return in case instruction is not from "FP-relative load/store group"; in any case tho i think it makes sense to change it first and care about details later

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp [hunk 10]
```diff
@@ -72,78 +85,69 @@ bool CDMRegisterInfo::eliminateFrameIndex(MachineBasicBlock::iterator II,
...
+      std::map<unsigned, std::pair<unsigned, unsigned>>::const_iterator(
+          SubstitutionOpcsTable.find(
+              MI.getOpcode())); // because inline gods said so
+
+  if (OpcodeFind == SubstitutionOpcsTable.end())
+    return false; // no instruction to change
+
+  auto [SubstitutionOpc, MemSize] = OpcodeFind->second;
+
+  if ((FpOffset > MemSize * 64 - 1) || (FpOffset < MemSize * -64)) {
```
[the remark this answers is not in the document]
Comment (ky1e-cyber) [reply llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: momentarily retardness (it is constant actually)

File: llvm/lib/Target/CDM/CDMRegisterInfo.cpp (hunk 8 above)
Comment (ky1e-cyber) [reply llvm/lib/Target/CDM/CDMRegisterInfo.cpp]: i don't know how to tackle it yet, calling conv tablegen seems to be kinda "detached" from others; i'll open when i have an idea (it doesn't matter for now anyway)
